# Generated by Django 5.2.14 on 2026-05-11 03:13

import django.db.models.deletion
import negocio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_tentativa', models.DateField()),
                ('numero_invitados', models.PositiveIntegerField(validators=[negocio.validators.validate_positive_integer])),
                ('tipo_servicio', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicio_completo', 'Servicio completo')], max_length=30)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('confirmada', 'Confirmada'), ('convertida', 'Convertida'), ('descartada', 'Descartada')], default='nueva', max_length=20)),
                ('total_estimado', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='negocio.cliente')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='negocio.paquete')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='negocio.tipoevento')),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_invitados__gt', 0)), name='cotizacion_numero_invitados_positivo'), models.CheckConstraint(condition=models.Q(('total_estimado__gte', 0)), name='cotizacion_total_estimado_no_negativo')],
            },
        ),
    ]
