# Generated by Django 5.2.14 on 2026-05-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_cotizacion_es_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_servicio',
            field=models.CharField(choices=[('alquiler', 'Alquiler del local'), ('servicio_completo', 'Servicio completo'), ('no_seguro', 'Aun no estoy seguro')], max_length=30),
        ),
    ]
