# Generated by Django 5.2.14 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0004_persona_identity_foundation"),
        ("comercial", "0003_alter_cotizacion_tipo_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="origen",
            field=models.CharField(
                choices=[
                    ("formulario_publico", "Formulario público"),
                    ("cotizacion_manual", "Cotización manual"),
                ],
                default="cotizacion_manual",
                max_length=30,
            ),
        ),
    ]
