# Generated by Django 5.2.14 on 2026-07-23

import negocio.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comercial", "0007_cotizacion_tipo_servicio_paquete_coherente"),
        ("negocio", "0008_catalogo_real_y_retiro_tipo_paquete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cotizacion",
            name="cotizacion_tipo_servicio_paquete_coherente",
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total_estimado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[negocio.validators.validate_non_negative],
            ),
        ),
        migrations.AddConstraint(
            model_name="cotizacion",
            constraint=models.CheckConstraint(
                condition=models.Q(oferta_requiere_revision=True)
                | models.Q(tipo_servicio="alquiler", paquete__isnull=True)
                | models.Q(
                    tipo_servicio="servicio_completo",
                    paquete__isnull=False,
                )
                | models.Q(
                    origen="formulario_publico",
                    tipo_servicio="servicio_completo",
                    paquete__isnull=True,
                )
                | models.Q(tipo_servicio="no_estoy_seguro"),
                name="cotizacion_tipo_servicio_paquete_coherente",
            ),
        ),
    ]
