# Generated by Django 5.2.14 on 2026-07-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_precotizacion_publica_sin_paquete'),
        ('negocio', '0008_catalogo_real_y_retiro_tipo_paquete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', 'fecha_tentativa'], name='cotiz_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['persona', '-creado_en'], name='cotiz_persona_crea_idx'),
        ),
    ]
