# Generated by Django 5.2.14 on 2026-05-11 03:13

import negocio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30, validators=[negocio.validators.validate_phone])),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('tarifa_base_alquiler', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('invitados_incluidos_alquiler', models.PositiveIntegerField(validators=[negocio.validators.validate_positive_integer])),
                ('costo_invitado_adicional', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('capacidad_maxima', models.PositiveIntegerField(validators=[negocio.validators.validate_positive_integer])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre_negocio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='configuracion_negocio_unica_activa'), models.CheckConstraint(condition=models.Q(('tarifa_base_alquiler__gte', 0)), name='config_tarifa_base_no_negativa'), models.CheckConstraint(condition=models.Q(('costo_invitado_adicional__gte', 0)), name='config_costo_invitado_adicional_no_negativo'), models.CheckConstraint(condition=models.Q(('invitados_incluidos_alquiler__gt', 0)), name='config_invitados_incluidos_positivo'), models.CheckConstraint(condition=models.Q(('capacidad_maxima__gt', 0)), name='config_capacidad_maxima_positiva')],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_servicio', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicio_completo', 'Servicio completo')], max_length=30)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_por_persona__gte', 0)), name='paquete_precio_por_persona_no_negativo')],
            },
        ),
    ]
