# Generated by Django 5.2.14 on 2026-05-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_demo',
            field=models.BooleanField(default=False),
        ),
    ]
