# Generated by Django 5.2.14 on 2026-05-20 02:35

import negocio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_cliente_es_demo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuracionnegocio',
            name='config_capacidad_maxima_positiva',
        ),
        migrations.RemoveField(
            model_name='configuracionnegocio',
            name='capacidad_maxima',
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='whatsapp_negocio',
            field=models.CharField(blank=True, max_length=10, validators=[negocio.validators.validate_whatsapp_ecuador]),
        ),
    ]
