# Generated by Django 5.2.14 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0003_remove_configuracionnegocio_config_capacidad_maxima_positiva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="origen",
            field=models.CharField(
                choices=[
                    ("formulario_publico", "Formulario público"),
                    ("cotizacion_manual", "Cotización manual"),
                    ("contrato_directo", "Contrato directo"),
                    ("registro_manual", "Registro manual"),
                ],
                default="registro_manual",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono_normalizado",
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="NombrePersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("nombre_normalizado", models.CharField(editable=False, max_length=150)),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("formulario_publico", "Formulario público"),
                            ("cotizacion_manual", "Cotización manual"),
                            ("contrato_directo", "Contrato directo"),
                            ("registro_manual", "Registro manual"),
                        ],
                        default="registro_manual",
                        max_length=30,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nombres_utilizados",
                        to="negocio.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cliente", "nombre_normalizado"),
                        name="nombre_persona_unico_por_cliente",
                    )
                ],
            },
        ),
    ]
