# Generated by Django 5.2.14 on 2026-07-22

import re
import unicodedata

from django.db import migrations, models


def normalize_phone(value):
    digits = re.sub(r"[^0-9]", "", value or "")
    if digits.startswith("00"):
        digits = digits[2:]
    if len(digits) == 10 and digits.startswith("0"):
        digits = f"593{digits[1:]}"
    return digits


def normalize_name(value):
    value = " ".join((value or "").strip().split()).casefold()
    return "".join(
        character
        for character in unicodedata.normalize("NFKD", value)
        if not unicodedata.combining(character)
    )


def merge_notes(current, extra, source_id):
    current = (current or "").strip()
    extra = (extra or "").strip()
    if not extra or extra in current:
        return current
    block = f"Registro consolidado #{source_id}:\n{extra}"
    return f"{current}\n\n{block}".strip() if current else block


def consolidate_existing_people(apps, schema_editor):
    Cliente = apps.get_model("negocio", "Cliente")
    NombrePersona = apps.get_model("negocio", "NombrePersona")
    Cotizacion = apps.get_model("comercial", "Cotizacion")
    Contrato = apps.get_model("financiero", "Contrato")

    groups = {}
    for person in Cliente.objects.all().order_by("creado_en", "id"):
        groups.setdefault(normalize_phone(person.telefono), []).append(person)

    for normalized_phone, people in groups.items():
        canonical = people[0]
        canonical_name = normalize_name(canonical.nombre)
        email = canonical.correo
        notes = canonical.observaciones
        is_demo = all(person.es_demo for person in people)
        created_at = min(person.creado_en for person in people)
        updated_at = max(person.actualizado_en for person in people)

        for duplicate in people[1:]:
            alias_normalized = normalize_name(duplicate.nombre)
            if alias_normalized and alias_normalized != canonical_name:
                alias, created = NombrePersona.objects.get_or_create(
                    cliente_id=canonical.id,
                    nombre_normalizado=alias_normalized,
                    defaults={
                        "nombre": duplicate.nombre,
                        "origen": duplicate.origen,
                    },
                )
                if created:
                    NombrePersona.objects.filter(pk=alias.pk).update(
                        creado_en=duplicate.creado_en,
                        actualizado_en=duplicate.creado_en,
                    )
            if not email and duplicate.correo:
                email = duplicate.correo
            elif duplicate.correo and duplicate.correo != email:
                notes = merge_notes(
                    notes,
                    f"Correo alternativo: {duplicate.correo}",
                    duplicate.id,
                )
            notes = merge_notes(notes, duplicate.observaciones, duplicate.id)
            Cotizacion.objects.filter(cliente_id=duplicate.id).update(cliente_id=canonical.id)
            Contrato.objects.filter(cliente_id=duplicate.id).update(cliente_id=canonical.id)

        Cliente.objects.filter(pk=canonical.id).update(
            telefono_normalizado=normalized_phone,
            correo=email,
            observaciones=notes,
            es_demo=is_demo,
            creado_en=created_at,
            actualizado_en=updated_at,
        )
        if len(people) > 1:
            Cliente.objects.filter(id__in=[item.id for item in people[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0004_cotizacion_origen"),
        ("financiero", "0003_costodirecto_eliminado_costodirecto_eliminado_en_and_more"),
        ("negocio", "0004_persona_identity_foundation"),
    ]

    operations = [
        migrations.RunPython(consolidate_existing_people, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cliente",
            name="telefono_normalizado",
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
