# Generated by Django 5.2.14 on 2026-05-11 03:13

import django.db.models.deletion
import financiero.validators
import negocio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_evento', models.DateField()),
                ('numero_invitados', models.PositiveIntegerField(validators=[negocio.validators.validate_positive_integer])),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('estado_contrato', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='negocio.cliente')),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='comercial.cotizacion')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='negocio.paquete')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='negocio.tipoevento')),
            ],
            options={
                'ordering': ['-fecha_evento', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_directos', to='financiero.contrato')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[negocio.validators.validate_non_negative])),
                ('mes', models.PositiveSmallIntegerField(validators=[financiero.validators.validate_month])),
                ('anio', models.PositiveIntegerField(validators=[financiero.validators.validate_year])),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-anio', '-mes', 'concepto'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='gasto_fijo_valor_no_negativo'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='gasto_fijo_mes_valido')],
            },
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('numero_invitados__gt', 0)), name='contrato_numero_invitados_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('valor_final__gte', 0)), name='contrato_valor_final_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('monto_abonado__gte', 0)), name='contrato_monto_abonado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('monto_abonado__lte', models.F('valor_final'))), name='contrato_monto_abonado_no_supera_valor_final'),
        ),
        migrations.AddConstraint(
            model_name='costodirecto',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='costo_directo_valor_no_negativo'),
        ),
    ]
