# Generated by Django 5.2.14 on 2026-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_contrato_es_demo_costodirecto_es_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costodirecto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costodirecto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastofijomensual',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gastofijomensual',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
