# Generated by Django 5.2.14 on 2026-07-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_cotizacion_cotiz_estado_fecha_idx_and_more'),
        ('financiero', '0006_tipo_servicio_y_oferta_historica'),
        ('negocio', '0008_catalogo_real_y_retiro_tipo_paquete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado_contrato', 'fecha_evento'], name='contrato_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado_pago', 'fecha_evento'], name='contrato_pago_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='costodirecto',
            index=models.Index(fields=['eliminado', 'fecha'], name='costo_activo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='costodirecto',
            index=models.Index(fields=['contrato', 'eliminado'], name='costo_contrato_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='gastoadicional',
            index=models.Index(fields=['eliminado', 'fecha'], name='gasto_adic_act_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['activo', 'inicio_periodo', 'fin_periodo'], name='gasto_rec_vigencia_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrenteajuste',
            index=models.Index(fields=['periodo', 'eliminado'], name='gasto_ajuste_periodo_idx'),
        ),
    ]
